FROM gcr.io/distroless/base-debian11
ARG BINARY_NAME

USER nonroot:nonroot

EXPOSE 8080

COPY --chown=nonroot:nonroot src/web /web
COPY --chown=nonroot:nonroot --chmod=755 ${BINARY_NAME} /harmony-go

ENTRYPOINT [ "/harmony-go" ]