# ----- BASE
FROM golang:1.23-alpine AS build-base

ENV SRC_DIR=src

# ----- BUILD
FROM build-base AS build-stage

WORKDIR /app

COPY ${SRC_DIR}/go.mod ${SRC_DIR}/go.sum ./
RUN go mod download

COPY ${SRC_DIR}/*.go ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /harmony-go

# ----- RELEASE
FROM gcr.io/distroless/base-debian11 AS release-stage

ENV SRC_DIR=src

WORKDIR /

COPY --from=build-stage /harmony-go /harmony-go
COPY ${SRC_DIR}/web /web 

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/harmony-go"]