name: Continuous Delivery

on:
  pull_request:
    branches:
      - 'main'

  workflow_dispatch:

env:
  IMAGE_NAME: 'harmony-go'

jobs:
  build: # TODO: add caching
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with: 
          go-version-file: 'src/go.mod'
          cache-dependency-path: |
            src/go.sum 
          # go-version: '1.23.5'

      - name: Go module dependencies
        working-directory: ./src
        run: |
          go mod download

      - name: Build
        working-directory: ./src
        run: |
          go build -o harmony-go
      
      - uses: actions/upload-artifact@v4
        with:
          name: harmony-bin
          path: src/harmony-go

  release:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v4

      - name: Install YC CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash

      - name : Run SSH Tunnel
        run: |
          mkdir -p ./.ssh
          touch ./.ssh/bastion && chmod 600 ./.ssh/bastion
          echo "${{ secrets.BASTION_KEY }}" > ./.ssh/bastion

          ssh -f -N \
            -i "./.ssh/bastion" \
            -D 1080 \
            -o StrictHostKeyChecking=no \
            ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOSTNAME }}

      - name: Check pods
        run: |
          touch ./SA_KEY && chmod 600 ./SA_KEY
          echo "${{ secrets.SA_KEY }}" > ./SA_KEY

          yc config profile create sa-profile
          yc config set service-account-key ./SA_KEY
          export YC_TOKEN=$(yc iam create-token)
          rm -rf ./SA_KEY

          yc managed-kubernetes cluster get-credentials --internal --name ${{ vars.CLUSTER_NAME }}
          kubectl get pods -A