name: Continuous Delivery

on:
  pull_request:
    branches:
      - 'main'

  workflow_dispatch:

env:
  IMAGE_NAME: 'harmony-go'

jobs:
  build: # TODO: add caching
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with: 
          go-version-file: 'src/go.mod'
          cache-dependency-path: |
            src/go.sum 
          # go-version: '1.23.5'

      - name: Go module dependencies
        working-directory: ./src
        run: |
          go mod download

      - name: Build
        working-directory: ./src
        run: |
          go build -o harmony-go
      
      - uses: actions/upload-artifact@v4
        with:
          name: harmony-bin
          path: src/harmony-go

  release:
    runs-on: ubuntu:latest
    # needs: [ build ]
    steps:
      - uses: actions/checkout@v4

      - name: Check pods
        run: |
          touch ~/.ssh/bastion && echo "${{ secrets.BASTION_KEY }}" > ~/.ssh/bastion
          ssh -T -i "~/.ssh/bastion" ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOSTNAME }}
          echo "hello"