name: Build And Push

on:
  push:
    tags:
      - "v*.*.*"
    # branches: ["main"]

  workflow_dispatch:

env:
  IMAGE_NAME: "harmony-go"

jobs:
  push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup QEMU for Buildx
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Form Metadata for Image
        id: metadata
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo "IMAGE_ID=${IMAGE_ID}" >> $GITHUB_OUTPUT

          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest

          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build and Push 
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.metadata.outputs.IMAGE_ID }}:${{ steps.metadata.outputs.VERSION }}
          platforms: linux/amd64,linux/arm64
          target: release-stage
          file: Dockerfile.dev
          labels: |
            runnumber=${GITHUB_RUN_ID}
          cache-from: type=gha
          cache-to: type=gha,mode=max